# Staticmajor: Static analyzer to catch leaking resources & other bad code patterns
name: Detect leaking resources and bad code patterns
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run_staticmajor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.11'
          cache: true
      - name: Staticmajor action
        id: staticmajor
        uses: orijtech/staticmajor-action@main
        with:
          packages: ./...
          resleak: true
          structslop: false
          tests: false
